config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "todos#index"

  resources :todos
  get 'delete_completed', to: 'todos#delete_completed'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    enum status: { active: 0, complete: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: %i[edit update destroy show]

    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)

        if @todo.save!
            redirect_to root_path
        else
            render :new
        end
    end

    def update
        if @todo.update(todo_params)
            redirect_to root_path
        else
            render :edit
        end
    end

    def destroy
        if @todo.destroy
            redirect_to root_path
        else
            render :show
        end
    end

    def delete_completed
        Todo.where(status: 1).destroy_all
        redirect_to root_path
    end

    private

    def todo_params
        params.require(:todo).permit(:title, :description, :status)
    end

    def set_todo
        @todo = Todo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodosApp</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="container">
    <%= form_with model: @todo do |form| %>
    <%= form.label :title %><br>
    <%= form.text_field :title, required: true %><br>
    <%= form.label :description %><br>
    <%= form.text_area :description, size: "60x10" %><br>
    <% unless @todo.id.nil? %>
        <%= form.label :status %><br>
        <%= form.select :status, Todo.statuses.keys %>
    <% end %>
    <%= form.submit %>
    <% end %>
</div>

<%# <form class="container">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form> %>

app/views/todos/edit.html.erb
<%= render partial: 'form' %>

app/views/todos/index.html.erb
<%= link_to 'Create Todo', new_todo_path, class: "btn btn-primary"%>
<% @todos.map do |todo| %>
    <div>
        <h1><%= todo.title %></h1>
        <p><%= todo.description %></p>
        <%= link_to 'View', todo_path(todo.id), class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_todo_path(todo.id), class: "btn btn-primary" %>
    </div>
<% end %><br>
<% unless Todo.count.zero? %>
    <%= link_to 'Clear All Completed', delete_completed_path, class: "btn btn-danger" %>
<% end %>

app/views/todos/new.html.erb
<%= render partial: 'form' %>

app/views/todos/show.html.erb
<div>
    <h1><%= @todo.title %></h1>
    <p><%= @todo.description %></p>
    <p><%= @todo.status %></p>
    <%= link_to "Delete", { action: 'destroy', id: @todo.id } %>
</div>